# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=7, null=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('ordered_tables', models.ManyToManyField(related_name='table_order_check', to='tables.Table')),
            ],
        ),
    ]
